### PR TITLE
Bug fix/support integer parsing

### PR DESCRIPTION
**Pull request by betzrhodes**

### CODE REVIEW

**Comment by myurasov** [comment]
Numbers in exponential notation (allowed by JSON standard) may as well be treated as floats.

```
"1e30".tointeger() === -2147483648
"1e-2".tointeger() === 0
```

**Comment by jayeheffernan** [comment]
Hi Elizabeth,

I think the `||` in that last commit should be an `&&`, since we only want to parse as an int if there is no decimal point _and_ there is no "e".  Furthermore, another check for "E" would be appropriate, since the JSON spec allows both of "E" and "e" for exponential notation and `string.tofloat()` can handle both.

**Comment by jayeheffernan** [comment]
Oh, I see that's updated now, thanks

**Comment by betzrhodes** [comment]
yeah I just caught that.

**Comment by jayeheffernan** [comment]
These are some helpful changes and I approve, but for completeness, a check for capitals (`&& value.find("E") == null`) should be added before merging.

**Comment by jayeheffernan** [comment]
Looks great, this is ready to merge.

**Pull request merged**
